// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: eventstore.proto

package orisun

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_ASC  Direction = 0
	Direction_DESC Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	Direction_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_eventstore_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_eventstore_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{0}
}

type StorageBackend int32

const (
	StorageBackend_STORAGE_BACKEND_UNSPECIFIED  StorageBackend = 0
	StorageBackend_STORAGE_BACKEND_POSTGRES     StorageBackend = 1
	StorageBackend_STORAGE_BACKEND_SQLITE       StorageBackend = 2
	StorageBackend_STORAGE_BACKEND_FOUNDATIONDB StorageBackend = 3
)

// Enum value maps for StorageBackend.
var (
	StorageBackend_name = map[int32]string{
		0: "STORAGE_BACKEND_UNSPECIFIED",
		1: "STORAGE_BACKEND_POSTGRES",
		2: "STORAGE_BACKEND_SQLITE",
		3: "STORAGE_BACKEND_FOUNDATIONDB",
	}
	StorageBackend_value = map[string]int32{
		"STORAGE_BACKEND_UNSPECIFIED":  0,
		"STORAGE_BACKEND_POSTGRES":     1,
		"STORAGE_BACKEND_SQLITE":       2,
		"STORAGE_BACKEND_FOUNDATIONDB": 3,
	}
)

func (x StorageBackend) Enum() *StorageBackend {
	p := new(StorageBackend)
	*p = x
	return p
}

func (x StorageBackend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageBackend) Descriptor() protoreflect.EnumDescriptor {
	return file_eventstore_proto_enumTypes[1].Descriptor()
}

func (StorageBackend) Type() protoreflect.EnumType {
	return &file_eventstore_proto_enumTypes[1]
}

func (x StorageBackend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageBackend.Descriptor instead.
func (StorageBackend) EnumDescriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{1}
}

type ServerCapability int32

const (
	ServerCapability_SERVER_CAPABILITY_UNSPECIFIED                 ServerCapability = 0
	ServerCapability_SERVER_CAPABILITY_COMMAND_CONTEXT_CONSISTENCY ServerCapability = 1
	ServerCapability_SERVER_CAPABILITY_CATCH_UP_SUBSCRIPTIONS      ServerCapability = 2
	ServerCapability_SERVER_CAPABILITY_INDEX_MANAGEMENT            ServerCapability = 3
	ServerCapability_SERVER_CAPABILITY_BOUNDARY_CATALOG            ServerCapability = 4
	ServerCapability_SERVER_CAPABILITY_GRPC_HEALTH                 ServerCapability = 5
)

// Enum value maps for ServerCapability.
var (
	ServerCapability_name = map[int32]string{
		0: "SERVER_CAPABILITY_UNSPECIFIED",
		1: "SERVER_CAPABILITY_COMMAND_CONTEXT_CONSISTENCY",
		2: "SERVER_CAPABILITY_CATCH_UP_SUBSCRIPTIONS",
		3: "SERVER_CAPABILITY_INDEX_MANAGEMENT",
		4: "SERVER_CAPABILITY_BOUNDARY_CATALOG",
		5: "SERVER_CAPABILITY_GRPC_HEALTH",
	}
	ServerCapability_value = map[string]int32{
		"SERVER_CAPABILITY_UNSPECIFIED":                 0,
		"SERVER_CAPABILITY_COMMAND_CONTEXT_CONSISTENCY": 1,
		"SERVER_CAPABILITY_CATCH_UP_SUBSCRIPTIONS":      2,
		"SERVER_CAPABILITY_INDEX_MANAGEMENT":            3,
		"SERVER_CAPABILITY_BOUNDARY_CATALOG":            4,
		"SERVER_CAPABILITY_GRPC_HEALTH":                 5,
	}
)

func (x ServerCapability) Enum() *ServerCapability {
	p := new(ServerCapability)
	*p = x
	return p
}

func (x ServerCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_eventstore_proto_enumTypes[2].Descriptor()
}

func (ServerCapability) Type() protoreflect.EnumType {
	return &file_eventstore_proto_enumTypes[2]
}

func (x ServerCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerCapability.Descriptor instead.
func (ServerCapability) EnumDescriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{2}
}

type ValueType int32

const (
	ValueType_TEXT        ValueType = 0
	ValueType_NUMERIC     ValueType = 1
	ValueType_BOOLEAN     ValueType = 2
	ValueType_TIMESTAMPTZ ValueType = 3
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "TEXT",
		1: "NUMERIC",
		2: "BOOLEAN",
		3: "TIMESTAMPTZ",
	}
	ValueType_value = map[string]int32{
		"TEXT":        0,
		"NUMERIC":     1,
		"BOOLEAN":     2,
		"TIMESTAMPTZ": 3,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_eventstore_proto_enumTypes[3].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_eventstore_proto_enumTypes[3]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{3}
}

type ConditionCombinator int32

const (
	ConditionCombinator_AND ConditionCombinator = 0
	ConditionCombinator_OR  ConditionCombinator = 1
)

// Enum value maps for ConditionCombinator.
var (
	ConditionCombinator_name = map[int32]string{
		0: "AND",
		1: "OR",
	}
	ConditionCombinator_value = map[string]int32{
		"AND": 0,
		"OR":  1,
	}
)

func (x ConditionCombinator) Enum() *ConditionCombinator {
	p := new(ConditionCombinator)
	*p = x
	return p
}

func (x ConditionCombinator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionCombinator) Descriptor() protoreflect.EnumDescriptor {
	return file_eventstore_proto_enumTypes[4].Descriptor()
}

func (ConditionCombinator) Type() protoreflect.EnumType {
	return &file_eventstore_proto_enumTypes[4]
}

func (x ConditionCombinator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionCombinator.Descriptor instead.
func (ConditionCombinator) EnumDescriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{4}
}

type IndexState int32

const (
	IndexState_INDEX_STATE_UNSPECIFIED IndexState = 0
	IndexState_INDEX_STATE_BUILDING    IndexState = 1
	IndexState_INDEX_STATE_READY       IndexState = 2
)

// Enum value maps for IndexState.
var (
	IndexState_name = map[int32]string{
		0: "INDEX_STATE_UNSPECIFIED",
		1: "INDEX_STATE_BUILDING",
		2: "INDEX_STATE_READY",
	}
	IndexState_value = map[string]int32{
		"INDEX_STATE_UNSPECIFIED": 0,
		"INDEX_STATE_BUILDING":    1,
		"INDEX_STATE_READY":       2,
	}
)

func (x IndexState) Enum() *IndexState {
	p := new(IndexState)
	*p = x
	return p
}

func (x IndexState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexState) Descriptor() protoreflect.EnumDescriptor {
	return file_eventstore_proto_enumTypes[5].Descriptor()
}

func (IndexState) Type() protoreflect.EnumType {
	return &file_eventstore_proto_enumTypes[5]
}

func (x IndexState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexState.Descriptor instead.
func (IndexState) EnumDescriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{5}
}

type Position struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommitPosition  int64                  `protobuf:"varint,1,opt,name=commit_position,json=commitPosition,proto3" json:"commit_position,omitempty"`
	PreparePosition int64                  `protobuf:"varint,2,opt,name=prepare_position,json=preparePosition,proto3" json:"prepare_position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_eventstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetCommitPosition() int64 {
	if x != nil {
		return x.CommitPosition
	}
	return 0
}

func (x *Position) GetPreparePosition() int64 {
	if x != nil {
		return x.PreparePosition
	}
	return 0
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_eventstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Criterion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Criterion) Reset() {
	*x = Criterion{}
	mi := &file_eventstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Criterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Criterion) ProtoMessage() {}

func (x *Criterion) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Criterion.ProtoReflect.Descriptor instead.
func (*Criterion) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{2}
}

func (x *Criterion) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criteria      []*Criterion           `protobuf:"bytes,1,rep,name=criteria,proto3" json:"criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_eventstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{3}
}

func (x *Query) GetCriteria() []*Criterion {
	if x != nil {
		return x.Criteria
	}
	return nil
}

type EventToSave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventToSave) Reset() {
	*x = EventToSave{}
	mi := &file_eventstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventToSave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventToSave) ProtoMessage() {}

func (x *EventToSave) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventToSave.ProtoReflect.Descriptor instead.
func (*EventToSave) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{4}
}

func (x *EventToSave) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventToSave) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventToSave) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *EventToSave) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Position      *Position              `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	DateCreated   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_eventstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Event) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Event) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Event) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.DateCreated
	}
	return nil
}

type WriteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogPosition   *Position              `protobuf:"bytes,1,opt,name=log_position,json=logPosition,proto3" json:"log_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResult) Reset() {
	*x = WriteResult{}
	mi := &file_eventstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResult) ProtoMessage() {}

func (x *WriteResult) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResult.ProtoReflect.Descriptor instead.
func (*WriteResult) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{6}
}

func (x *WriteResult) GetLogPosition() *Position {
	if x != nil {
		return x.LogPosition
	}
	return nil
}

type SaveQuery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpectedPosition *Position              `protobuf:"bytes,1,opt,name=expected_position,json=expectedPosition,proto3" json:"expected_position,omitempty"`
	SubsetQuery      *Query                 `protobuf:"bytes,2,opt,name=subsetQuery,proto3" json:"subsetQuery,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SaveQuery) Reset() {
	*x = SaveQuery{}
	mi := &file_eventstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveQuery) ProtoMessage() {}

func (x *SaveQuery) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveQuery.ProtoReflect.Descriptor instead.
func (*SaveQuery) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{7}
}

func (x *SaveQuery) GetExpectedPosition() *Position {
	if x != nil {
		return x.ExpectedPosition
	}
	return nil
}

func (x *SaveQuery) GetSubsetQuery() *Query {
	if x != nil {
		return x.SubsetQuery
	}
	return nil
}

type SaveEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundary      string                 `protobuf:"bytes,2,opt,name=boundary,proto3" json:"boundary,omitempty"`
	Query         *SaveQuery             `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Events        []*EventToSave         `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveEventsRequest) Reset() {
	*x = SaveEventsRequest{}
	mi := &file_eventstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveEventsRequest) ProtoMessage() {}

func (x *SaveEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveEventsRequest.ProtoReflect.Descriptor instead.
func (*SaveEventsRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{8}
}

func (x *SaveEventsRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

func (x *SaveEventsRequest) GetQuery() *SaveQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SaveEventsRequest) GetEvents() []*EventToSave {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	FromPosition  *Position              `protobuf:"bytes,2,opt,name=from_position,json=fromPosition,proto3" json:"from_position,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Direction     Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=orisun.Direction" json:"direction,omitempty"`
	Boundary      string                 `protobuf:"bytes,5,opt,name=boundary,proto3" json:"boundary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_eventstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{9}
}

func (x *GetEventsRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GetEventsRequest) GetFromPosition() *Position {
	if x != nil {
		return x.FromPosition
	}
	return nil
}

func (x *GetEventsRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetEventsRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_ASC
}

func (x *GetEventsRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_eventstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{10}
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type CatchUpSubscribeToEventStoreRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AfterPosition  *Position              `protobuf:"bytes,1,opt,name=after_position,json=afterPosition,proto3" json:"after_position,omitempty"`
	Query          *Query                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	SubscriberName string                 `protobuf:"bytes,3,opt,name=subscriber_name,json=subscriberName,proto3" json:"subscriber_name,omitempty"`
	Boundary       string                 `protobuf:"bytes,4,opt,name=boundary,proto3" json:"boundary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CatchUpSubscribeToEventStoreRequest) Reset() {
	*x = CatchUpSubscribeToEventStoreRequest{}
	mi := &file_eventstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchUpSubscribeToEventStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchUpSubscribeToEventStoreRequest) ProtoMessage() {}

func (x *CatchUpSubscribeToEventStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchUpSubscribeToEventStoreRequest.ProtoReflect.Descriptor instead.
func (*CatchUpSubscribeToEventStoreRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{11}
}

func (x *CatchUpSubscribeToEventStoreRequest) GetAfterPosition() *Position {
	if x != nil {
		return x.AfterPosition
	}
	return nil
}

func (x *CatchUpSubscribeToEventStoreRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *CatchUpSubscribeToEventStoreRequest) GetSubscriberName() string {
	if x != nil {
		return x.SubscriberName
	}
	return ""
}

func (x *CatchUpSubscribeToEventStoreRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_eventstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{12}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_eventstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{13}
}

type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_eventstore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{14}
}

type GetServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GitCommit     string                 `protobuf:"bytes,2,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	BuildTime     string                 `protobuf:"bytes,3,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	Backend       StorageBackend         `protobuf:"varint,4,opt,name=backend,proto3,enum=orisun.StorageBackend" json:"backend,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Capabilities  []ServerCapability     `protobuf:"varint,6,rep,packed,name=capabilities,proto3,enum=orisun.ServerCapability" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	mi := &file_eventstore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{15}
}

func (x *GetServerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetServerInfoResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *GetServerInfoResponse) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *GetServerInfoResponse) GetBackend() StorageBackend {
	if x != nil {
		return x.Backend
	}
	return StorageBackend_STORAGE_BACKEND_UNSPECIFIED
}

func (x *GetServerInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetServerInfoResponse) GetCapabilities() []ServerCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// GetLatestByCriteria returns the latest event matching each criterion,
// assembled by the server from ONE consistent read snapshot, plus the
// context_position to use as SaveEvents.query.expected_position with the same
// combined criteria. Assembling the same context from independent GetEvents
// calls is not equivalent: an event can commit between the calls with a
// position below the observed maximum, and a scalar expected position cannot
// detect that.
type GetLatestByCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundary      string                 `protobuf:"bytes,1,opt,name=boundary,proto3" json:"boundary,omitempty"`
	Criteria      []*Criterion           `protobuf:"bytes,2,rep,name=criteria,proto3" json:"criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestByCriteriaRequest) Reset() {
	*x = GetLatestByCriteriaRequest{}
	mi := &file_eventstore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestByCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestByCriteriaRequest) ProtoMessage() {}

func (x *GetLatestByCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestByCriteriaRequest.ProtoReflect.Descriptor instead.
func (*GetLatestByCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{16}
}

func (x *GetLatestByCriteriaRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

func (x *GetLatestByCriteriaRequest) GetCriteria() []*Criterion {
	if x != nil {
		return x.Criteria
	}
	return nil
}

type LatestCriterionResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Criterion *Criterion             `protobuf:"bytes,1,opt,name=criterion,proto3" json:"criterion,omitempty"`
	// Unset when no event matches the criterion.
	Event         *Event `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestCriterionResult) Reset() {
	*x = LatestCriterionResult{}
	mi := &file_eventstore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestCriterionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestCriterionResult) ProtoMessage() {}

func (x *LatestCriterionResult) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestCriterionResult.ProtoReflect.Descriptor instead.
func (*LatestCriterionResult) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{17}
}

func (x *LatestCriterionResult) GetCriterion() *Criterion {
	if x != nil {
		return x.Criterion
	}
	return nil
}

func (x *LatestCriterionResult) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type GetLatestByCriteriaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One result per request criterion, in request order.
	Results []*LatestCriterionResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Max position across the events observed in the same read snapshot;
	// the not-exists sentinel (-1, -1) when nothing matched.
	ContextPosition *Position `protobuf:"bytes,2,opt,name=context_position,json=contextPosition,proto3" json:"context_position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLatestByCriteriaResponse) Reset() {
	*x = GetLatestByCriteriaResponse{}
	mi := &file_eventstore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestByCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestByCriteriaResponse) ProtoMessage() {}

func (x *GetLatestByCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestByCriteriaResponse.ProtoReflect.Descriptor instead.
func (*GetLatestByCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{18}
}

func (x *GetLatestByCriteriaResponse) GetResults() []*LatestCriterionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetLatestByCriteriaResponse) GetContextPosition() *Position {
	if x != nil {
		return x.ContextPosition
	}
	return nil
}

// IndexField describes one key to include in the index expression.
// Multiple fields produce a composite index.
type IndexField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonKey       string                 `protobuf:"bytes,1,opt,name=json_key,json=jsonKey,proto3" json:"json_key,omitempty"`
	ValueType     ValueType              `protobuf:"varint,2,opt,name=value_type,json=valueType,proto3,enum=orisun.ValueType" json:"value_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexField) Reset() {
	*x = IndexField{}
	mi := &file_eventstore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexField) ProtoMessage() {}

func (x *IndexField) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexField.ProtoReflect.Descriptor instead.
func (*IndexField) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{19}
}

func (x *IndexField) GetJsonKey() string {
	if x != nil {
		return x.JsonKey
	}
	return ""
}

func (x *IndexField) GetValueType() ValueType {
	if x != nil {
		return x.ValueType
	}
	return ValueType_TEXT
}

// IndexCondition describes one predicate in the partial-index filter.
// Multiple conditions are combined with condition_combinator.
type IndexCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexCondition) Reset() {
	*x = IndexCondition{}
	mi := &file_eventstore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexCondition) ProtoMessage() {}

func (x *IndexCondition) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexCondition.ProtoReflect.Descriptor instead.
func (*IndexCondition) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{20}
}

func (x *IndexCondition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IndexCondition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *IndexCondition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateIndexRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Boundary            string                 `protobuf:"bytes,1,opt,name=boundary,proto3" json:"boundary,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fields              []*IndexField          `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Conditions          []*IndexCondition      `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	ConditionCombinator ConditionCombinator    `protobuf:"varint,5,opt,name=condition_combinator,json=conditionCombinator,proto3,enum=orisun.ConditionCombinator" json:"condition_combinator,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateIndexRequest) Reset() {
	*x = CreateIndexRequest{}
	mi := &file_eventstore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexRequest) ProtoMessage() {}

func (x *CreateIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{21}
}

func (x *CreateIndexRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

func (x *CreateIndexRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIndexRequest) GetFields() []*IndexField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CreateIndexRequest) GetConditions() []*IndexCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *CreateIndexRequest) GetConditionCombinator() ConditionCombinator {
	if x != nil {
		return x.ConditionCombinator
	}
	return ConditionCombinator_AND
}

type CreateIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexResponse) Reset() {
	*x = CreateIndexResponse{}
	mi := &file_eventstore_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexResponse) ProtoMessage() {}

func (x *CreateIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexResponse.ProtoReflect.Descriptor instead.
func (*CreateIndexResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{22}
}

type DropIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundary      string                 `protobuf:"bytes,1,opt,name=boundary,proto3" json:"boundary,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropIndexRequest) Reset() {
	*x = DropIndexRequest{}
	mi := &file_eventstore_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropIndexRequest) ProtoMessage() {}

func (x *DropIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropIndexRequest.ProtoReflect.Descriptor instead.
func (*DropIndexRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{23}
}

func (x *DropIndexRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

func (x *DropIndexRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropIndexResponse) Reset() {
	*x = DropIndexResponse{}
	mi := &file_eventstore_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropIndexResponse) ProtoMessage() {}

func (x *DropIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropIndexResponse.ProtoReflect.Descriptor instead.
func (*DropIndexResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{24}
}

type IndexDefinition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields              []*IndexField          `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Conditions          []*IndexCondition      `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	ConditionCombinator ConditionCombinator    `protobuf:"varint,4,opt,name=condition_combinator,json=conditionCombinator,proto3,enum=orisun.ConditionCombinator" json:"condition_combinator,omitempty"`
	State               IndexState             `protobuf:"varint,5,opt,name=state,proto3,enum=orisun.IndexState" json:"state,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IndexDefinition) Reset() {
	*x = IndexDefinition{}
	mi := &file_eventstore_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDefinition) ProtoMessage() {}

func (x *IndexDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDefinition.ProtoReflect.Descriptor instead.
func (*IndexDefinition) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{25}
}

func (x *IndexDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexDefinition) GetFields() []*IndexField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *IndexDefinition) GetConditions() []*IndexCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *IndexDefinition) GetConditionCombinator() ConditionCombinator {
	if x != nil {
		return x.ConditionCombinator
	}
	return ConditionCombinator_AND
}

func (x *IndexDefinition) GetState() IndexState {
	if x != nil {
		return x.State
	}
	return IndexState_INDEX_STATE_UNSPECIFIED
}

type ListIndexesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundary      string                 `protobuf:"bytes,1,opt,name=boundary,proto3" json:"boundary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndexesRequest) Reset() {
	*x = ListIndexesRequest{}
	mi := &file_eventstore_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndexesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesRequest) ProtoMessage() {}

func (x *ListIndexesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesRequest.ProtoReflect.Descriptor instead.
func (*ListIndexesRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{26}
}

func (x *ListIndexesRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

type ListIndexesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indexes       []*IndexDefinition     `protobuf:"bytes,1,rep,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndexesResponse) Reset() {
	*x = ListIndexesResponse{}
	mi := &file_eventstore_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndexesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesResponse) ProtoMessage() {}

func (x *ListIndexesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesResponse.ProtoReflect.Descriptor instead.
func (*ListIndexesResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{27}
}

func (x *ListIndexesResponse) GetIndexes() []*IndexDefinition {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type GetIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundary      string                 `protobuf:"bytes,1,opt,name=boundary,proto3" json:"boundary,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexRequest) Reset() {
	*x = GetIndexRequest{}
	mi := &file_eventstore_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexRequest) ProtoMessage() {}

func (x *GetIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexRequest.ProtoReflect.Descriptor instead.
func (*GetIndexRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{28}
}

func (x *GetIndexRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

func (x *GetIndexRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *IndexDefinition       `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexResponse) Reset() {
	*x = GetIndexResponse{}
	mi := &file_eventstore_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexResponse) ProtoMessage() {}

func (x *GetIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexResponse.ProtoReflect.Descriptor instead.
func (*GetIndexResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{29}
}

func (x *GetIndexResponse) GetIndex() *IndexDefinition {
	if x != nil {
		return x.Index
	}
	return nil
}

var File_eventstore_proto protoreflect.FileDescriptor

const file_eventstore_proto_rawDesc = "" +
	"\n" +
	"\x10eventstore.proto\x12\x06orisun\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\bPosition\x12'\n" +
	"\x0fcommit_position\x18\x01 \x01(\x03R\x0ecommitPosition\x12)\n" +
	"\x10prepare_position\x18\x02 \x01(\x03R\x0fpreparePosition\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\",\n" +
	"\tCriterion\x12\x1f\n" +
	"\x04tags\x18\x01 \x03(\v2\v.orisun.TagR\x04tags\"6\n" +
	"\x05Query\x12-\n" +
	"\bcriteria\x18\x01 \x03(\v2\x11.orisun.CriterionR\bcriteria\"w\n" +
	"\vEventToSave\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"\xde\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12,\n" +
	"\bposition\x18\x06 \x01(\v2\x10.orisun.PositionR\bposition\x12=\n" +
	"\fdate_created\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\"B\n" +
	"\vWriteResult\x123\n" +
	"\flog_position\x18\x01 \x01(\v2\x10.orisun.PositionR\vlogPosition\"{\n" +
	"\tSaveQuery\x12=\n" +
	"\x11expected_position\x18\x01 \x01(\v2\x10.orisun.PositionR\x10expectedPosition\x12/\n" +
	"\vsubsetQuery\x18\x02 \x01(\v2\r.orisun.QueryR\vsubsetQuery\"\x85\x01\n" +
	"\x11SaveEventsRequest\x12\x1a\n" +
	"\bboundary\x18\x02 \x01(\tR\bboundary\x12'\n" +
	"\x05query\x18\x03 \x01(\v2\x11.orisun.SaveQueryR\x05query\x12+\n" +
	"\x06events\x18\x04 \x03(\v2\x13.orisun.EventToSaveR\x06events\"\xd1\x01\n" +
	"\x10GetEventsRequest\x12#\n" +
	"\x05query\x18\x01 \x01(\v2\r.orisun.QueryR\x05query\x125\n" +
	"\rfrom_position\x18\x02 \x01(\v2\x10.orisun.PositionR\ffromPosition\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12/\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x11.orisun.DirectionR\tdirection\x12\x1a\n" +
	"\bboundary\x18\x05 \x01(\tR\bboundary\":\n" +
	"\x11GetEventsResponse\x12%\n" +
	"\x06events\x18\x01 \x03(\v2\r.orisun.EventR\x06events\"\xc8\x01\n" +
	"#CatchUpSubscribeToEventStoreRequest\x127\n" +
	"\x0eafter_position\x18\x01 \x01(\v2\x10.orisun.PositionR\rafterPosition\x12#\n" +
	"\x05query\x18\x02 \x01(\v2\r.orisun.QueryR\x05query\x12'\n" +
	"\x0fsubscriber_name\x18\x03 \x01(\tR\x0esubscriberName\x12\x1a\n" +
	"\bboundary\x18\x04 \x01(\tR\bboundary\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\x16\n" +
	"\x14GetServerInfoRequest\"\xf8\x01\n" +
	"\x15GetServerInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x02 \x01(\tR\tgitCommit\x12\x1d\n" +
	"\n" +
	"build_time\x18\x03 \x01(\tR\tbuildTime\x120\n" +
	"\abackend\x18\x04 \x01(\x0e2\x16.orisun.StorageBackendR\abackend\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12<\n" +
	"\fcapabilities\x18\x06 \x03(\x0e2\x18.orisun.ServerCapabilityR\fcapabilities\"g\n" +
	"\x1aGetLatestByCriteriaRequest\x12\x1a\n" +
	"\bboundary\x18\x01 \x01(\tR\bboundary\x12-\n" +
	"\bcriteria\x18\x02 \x03(\v2\x11.orisun.CriterionR\bcriteria\"m\n" +
	"\x15LatestCriterionResult\x12/\n" +
	"\tcriterion\x18\x01 \x01(\v2\x11.orisun.CriterionR\tcriterion\x12#\n" +
	"\x05event\x18\x02 \x01(\v2\r.orisun.EventR\x05event\"\x93\x01\n" +
	"\x1bGetLatestByCriteriaResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.orisun.LatestCriterionResultR\aresults\x12;\n" +
	"\x10context_position\x18\x02 \x01(\v2\x10.orisun.PositionR\x0fcontextPosition\"Y\n" +
	"\n" +
	"IndexField\x12\x19\n" +
	"\bjson_key\x18\x01 \x01(\tR\ajsonKey\x120\n" +
	"\n" +
	"value_type\x18\x02 \x01(\x0e2\x11.orisun.ValueTypeR\tvalueType\"T\n" +
	"\x0eIndexCondition\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xf8\x01\n" +
	"\x12CreateIndexRequest\x12\x1a\n" +
	"\bboundary\x18\x01 \x01(\tR\bboundary\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x06fields\x18\x03 \x03(\v2\x12.orisun.IndexFieldR\x06fields\x126\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2\x16.orisun.IndexConditionR\n" +
	"conditions\x12N\n" +
	"\x14condition_combinator\x18\x05 \x01(\x0e2\x1b.orisun.ConditionCombinatorR\x13conditionCombinator\"\x15\n" +
	"\x13CreateIndexResponse\"B\n" +
	"\x10DropIndexRequest\x12\x1a\n" +
	"\bboundary\x18\x01 \x01(\tR\bboundary\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x13\n" +
	"\x11DropIndexResponse\"\x83\x02\n" +
	"\x0fIndexDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x06fields\x18\x02 \x03(\v2\x12.orisun.IndexFieldR\x06fields\x126\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2\x16.orisun.IndexConditionR\n" +
	"conditions\x12N\n" +
	"\x14condition_combinator\x18\x04 \x01(\x0e2\x1b.orisun.ConditionCombinatorR\x13conditionCombinator\x12(\n" +
	"\x05state\x18\x05 \x01(\x0e2\x12.orisun.IndexStateR\x05state\"0\n" +
	"\x12ListIndexesRequest\x12\x1a\n" +
	"\bboundary\x18\x01 \x01(\tR\bboundary\"H\n" +
	"\x13ListIndexesResponse\x121\n" +
	"\aindexes\x18\x01 \x03(\v2\x17.orisun.IndexDefinitionR\aindexes\"A\n" +
	"\x0fGetIndexRequest\x12\x1a\n" +
	"\bboundary\x18\x01 \x01(\tR\bboundary\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"A\n" +
	"\x10GetIndexResponse\x12-\n" +
	"\x05index\x18\x01 \x01(\v2\x17.orisun.IndexDefinitionR\x05index*\x1e\n" +
	"\tDirection\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x01*\x8d\x01\n" +
	"\x0eStorageBackend\x12\x1f\n" +
	"\x1bSTORAGE_BACKEND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18STORAGE_BACKEND_POSTGRES\x10\x01\x12\x1a\n" +
	"\x16STORAGE_BACKEND_SQLITE\x10\x02\x12 \n" +
	"\x1cSTORAGE_BACKEND_FOUNDATIONDB\x10\x03*\x89\x02\n" +
	"\x10ServerCapability\x12!\n" +
	"\x1dSERVER_CAPABILITY_UNSPECIFIED\x10\x00\x121\n" +
	"-SERVER_CAPABILITY_COMMAND_CONTEXT_CONSISTENCY\x10\x01\x12,\n" +
	"(SERVER_CAPABILITY_CATCH_UP_SUBSCRIPTIONS\x10\x02\x12&\n" +
	"\"SERVER_CAPABILITY_INDEX_MANAGEMENT\x10\x03\x12&\n" +
	"\"SERVER_CAPABILITY_BOUNDARY_CATALOG\x10\x04\x12!\n" +
	"\x1dSERVER_CAPABILITY_GRPC_HEALTH\x10\x05*@\n" +
	"\tValueType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\v\n" +
	"\aNUMERIC\x10\x01\x12\v\n" +
	"\aBOOLEAN\x10\x02\x12\x0f\n" +
	"\vTIMESTAMPTZ\x10\x03*&\n" +
	"\x13ConditionCombinator\x12\a\n" +
	"\x03AND\x10\x00\x12\x06\n" +
	"\x02OR\x10\x01*Z\n" +
	"\n" +
	"IndexState\x12\x1b\n" +
	"\x17INDEX_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INDEX_STATE_BUILDING\x10\x01\x12\x15\n" +
	"\x11INDEX_STATE_READY\x10\x022\xec\x05\n" +
	"\n" +
	"EventStore\x12>\n" +
	"\n" +
	"SaveEvents\x12\x19.orisun.SaveEventsRequest\x1a\x13.orisun.WriteResult\"\x00\x12B\n" +
	"\tGetEvents\x12\x18.orisun.GetEventsRequest\x1a\x19.orisun.GetEventsResponse\"\x00\x12`\n" +
	"\x13GetLatestByCriteria\x12\".orisun.GetLatestByCriteriaRequest\x1a#.orisun.GetLatestByCriteriaResponse\"\x00\x12Z\n" +
	"\x18CatchUpSubscribeToEvents\x12+.orisun.CatchUpSubscribeToEventStoreRequest\x1a\r.orisun.Event\"\x000\x01\x123\n" +
	"\x04Ping\x12\x13.orisun.PingRequest\x1a\x14.orisun.PingResponse\"\x00\x12N\n" +
	"\rGetServerInfo\x12\x1c.orisun.GetServerInfoRequest\x1a\x1d.orisun.GetServerInfoResponse\"\x00\x12H\n" +
	"\vCreateIndex\x12\x1a.orisun.CreateIndexRequest\x1a\x1b.orisun.CreateIndexResponse\"\x00\x12B\n" +
	"\tDropIndex\x12\x18.orisun.DropIndexRequest\x1a\x19.orisun.DropIndexResponse\"\x00\x12H\n" +
	"\vListIndexes\x12\x1a.orisun.ListIndexesRequest\x1a\x1b.orisun.ListIndexesResponse\"\x00\x12?\n" +
	"\bGetIndex\x12\x17.orisun.GetIndexRequest\x1a\x18.orisun.GetIndexResponse\"\x00BD\n" +
	"\x15com.orisun.eventstoreZ+github.com/OrisunLabs/Orisun/orisun/grpcapib\x06proto3"

var (
	file_eventstore_proto_rawDescOnce sync.Once
	file_eventstore_proto_rawDescData []byte
)

func file_eventstore_proto_rawDescGZIP() []byte {
	file_eventstore_proto_rawDescOnce.Do(func() {
		file_eventstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventstore_proto_rawDesc), len(file_eventstore_proto_rawDesc)))
	})
	return file_eventstore_proto_rawDescData
}

var file_eventstore_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_eventstore_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_eventstore_proto_goTypes = []any{
	(Direction)(0),                              // 0: orisun.Direction
	(StorageBackend)(0),                         // 1: orisun.StorageBackend
	(ServerCapability)(0),                       // 2: orisun.ServerCapability
	(ValueType)(0),                              // 3: orisun.ValueType
	(ConditionCombinator)(0),                    // 4: orisun.ConditionCombinator
	(IndexState)(0),                             // 5: orisun.IndexState
	(*Position)(nil),                            // 6: orisun.Position
	(*Tag)(nil),                                 // 7: orisun.Tag
	(*Criterion)(nil),                           // 8: orisun.Criterion
	(*Query)(nil),                               // 9: orisun.Query
	(*EventToSave)(nil),                         // 10: orisun.EventToSave
	(*Event)(nil),                               // 11: orisun.Event
	(*WriteResult)(nil),                         // 12: orisun.WriteResult
	(*SaveQuery)(nil),                           // 13: orisun.SaveQuery
	(*SaveEventsRequest)(nil),                   // 14: orisun.SaveEventsRequest
	(*GetEventsRequest)(nil),                    // 15: orisun.GetEventsRequest
	(*GetEventsResponse)(nil),                   // 16: orisun.GetEventsResponse
	(*CatchUpSubscribeToEventStoreRequest)(nil), // 17: orisun.CatchUpSubscribeToEventStoreRequest
	(*PingRequest)(nil),                         // 18: orisun.PingRequest
	(*PingResponse)(nil),                        // 19: orisun.PingResponse
	(*GetServerInfoRequest)(nil),                // 20: orisun.GetServerInfoRequest
	(*GetServerInfoResponse)(nil),               // 21: orisun.GetServerInfoResponse
	(*GetLatestByCriteriaRequest)(nil),          // 22: orisun.GetLatestByCriteriaRequest
	(*LatestCriterionResult)(nil),               // 23: orisun.LatestCriterionResult
	(*GetLatestByCriteriaResponse)(nil),         // 24: orisun.GetLatestByCriteriaResponse
	(*IndexField)(nil),                          // 25: orisun.IndexField
	(*IndexCondition)(nil),                      // 26: orisun.IndexCondition
	(*CreateIndexRequest)(nil),                  // 27: orisun.CreateIndexRequest
	(*CreateIndexResponse)(nil),                 // 28: orisun.CreateIndexResponse
	(*DropIndexRequest)(nil),                    // 29: orisun.DropIndexRequest
	(*DropIndexResponse)(nil),                   // 30: orisun.DropIndexResponse
	(*IndexDefinition)(nil),                     // 31: orisun.IndexDefinition
	(*ListIndexesRequest)(nil),                  // 32: orisun.ListIndexesRequest
	(*ListIndexesResponse)(nil),                 // 33: orisun.ListIndexesResponse
	(*GetIndexRequest)(nil),                     // 34: orisun.GetIndexRequest
	(*GetIndexResponse)(nil),                    // 35: orisun.GetIndexResponse
	(*timestamppb.Timestamp)(nil),               // 36: google.protobuf.Timestamp
}
var file_eventstore_proto_depIdxs = []int32{
	7,  // 0: orisun.Criterion.tags:type_name -> orisun.Tag
	8,  // 1: orisun.Query.criteria:type_name -> orisun.Criterion
	6,  // 2: orisun.Event.position:type_name -> orisun.Position
	36, // 3: orisun.Event.date_created:type_name -> google.protobuf.Timestamp
	6,  // 4: orisun.WriteResult.log_position:type_name -> orisun.Position
	6,  // 5: orisun.SaveQuery.expected_position:type_name -> orisun.Position
	9,  // 6: orisun.SaveQuery.subsetQuery:type_name -> orisun.Query
	13, // 7: orisun.SaveEventsRequest.query:type_name -> orisun.SaveQuery
	10, // 8: orisun.SaveEventsRequest.events:type_name -> orisun.EventToSave
	9,  // 9: orisun.GetEventsRequest.query:type_name -> orisun.Query
	6,  // 10: orisun.GetEventsRequest.from_position:type_name -> orisun.Position
	0,  // 11: orisun.GetEventsRequest.direction:type_name -> orisun.Direction
	11, // 12: orisun.GetEventsResponse.events:type_name -> orisun.Event
	6,  // 13: orisun.CatchUpSubscribeToEventStoreRequest.after_position:type_name -> orisun.Position
	9,  // 14: orisun.CatchUpSubscribeToEventStoreRequest.query:type_name -> orisun.Query
	1,  // 15: orisun.GetServerInfoResponse.backend:type_name -> orisun.StorageBackend
	2,  // 16: orisun.GetServerInfoResponse.capabilities:type_name -> orisun.ServerCapability
	8,  // 17: orisun.GetLatestByCriteriaRequest.criteria:type_name -> orisun.Criterion
	8,  // 18: orisun.LatestCriterionResult.criterion:type_name -> orisun.Criterion
	11, // 19: orisun.LatestCriterionResult.event:type_name -> orisun.Event
	23, // 20: orisun.GetLatestByCriteriaResponse.results:type_name -> orisun.LatestCriterionResult
	6,  // 21: orisun.GetLatestByCriteriaResponse.context_position:type_name -> orisun.Position
	3,  // 22: orisun.IndexField.value_type:type_name -> orisun.ValueType
	25, // 23: orisun.CreateIndexRequest.fields:type_name -> orisun.IndexField
	26, // 24: orisun.CreateIndexRequest.conditions:type_name -> orisun.IndexCondition
	4,  // 25: orisun.CreateIndexRequest.condition_combinator:type_name -> orisun.ConditionCombinator
	25, // 26: orisun.IndexDefinition.fields:type_name -> orisun.IndexField
	26, // 27: orisun.IndexDefinition.conditions:type_name -> orisun.IndexCondition
	4,  // 28: orisun.IndexDefinition.condition_combinator:type_name -> orisun.ConditionCombinator
	5,  // 29: orisun.IndexDefinition.state:type_name -> orisun.IndexState
	31, // 30: orisun.ListIndexesResponse.indexes:type_name -> orisun.IndexDefinition
	31, // 31: orisun.GetIndexResponse.index:type_name -> orisun.IndexDefinition
	14, // 32: orisun.EventStore.SaveEvents:input_type -> orisun.SaveEventsRequest
	15, // 33: orisun.EventStore.GetEvents:input_type -> orisun.GetEventsRequest
	22, // 34: orisun.EventStore.GetLatestByCriteria:input_type -> orisun.GetLatestByCriteriaRequest
	17, // 35: orisun.EventStore.CatchUpSubscribeToEvents:input_type -> orisun.CatchUpSubscribeToEventStoreRequest
	18, // 36: orisun.EventStore.Ping:input_type -> orisun.PingRequest
	20, // 37: orisun.EventStore.GetServerInfo:input_type -> orisun.GetServerInfoRequest
	27, // 38: orisun.EventStore.CreateIndex:input_type -> orisun.CreateIndexRequest
	29, // 39: orisun.EventStore.DropIndex:input_type -> orisun.DropIndexRequest
	32, // 40: orisun.EventStore.ListIndexes:input_type -> orisun.ListIndexesRequest
	34, // 41: orisun.EventStore.GetIndex:input_type -> orisun.GetIndexRequest
	12, // 42: orisun.EventStore.SaveEvents:output_type -> orisun.WriteResult
	16, // 43: orisun.EventStore.GetEvents:output_type -> orisun.GetEventsResponse
	24, // 44: orisun.EventStore.GetLatestByCriteria:output_type -> orisun.GetLatestByCriteriaResponse
	11, // 45: orisun.EventStore.CatchUpSubscribeToEvents:output_type -> orisun.Event
	19, // 46: orisun.EventStore.Ping:output_type -> orisun.PingResponse
	21, // 47: orisun.EventStore.GetServerInfo:output_type -> orisun.GetServerInfoResponse
	28, // 48: orisun.EventStore.CreateIndex:output_type -> orisun.CreateIndexResponse
	30, // 49: orisun.EventStore.DropIndex:output_type -> orisun.DropIndexResponse
	33, // 50: orisun.EventStore.ListIndexes:output_type -> orisun.ListIndexesResponse
	35, // 51: orisun.EventStore.GetIndex:output_type -> orisun.GetIndexResponse
	42, // [42:52] is the sub-list for method output_type
	32, // [32:42] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_eventstore_proto_init() }
func file_eventstore_proto_init() {
	if File_eventstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventstore_proto_rawDesc), len(file_eventstore_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eventstore_proto_goTypes,
		DependencyIndexes: file_eventstore_proto_depIdxs,
		EnumInfos:         file_eventstore_proto_enumTypes,
		MessageInfos:      file_eventstore_proto_msgTypes,
	}.Build()
	File_eventstore_proto = out.File
	file_eventstore_proto_goTypes = nil
	file_eventstore_proto_depIdxs = nil
}
